services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - treafik_proxy
      - socket_proxy
    volumes:
      - vw_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault-rtr.entrypoints=websecure"
      - "traefik.http.routers.vault-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.vault-rtr.rule=Host(`vault.balezeau.fr`)"
      - "traefik.http.routers.vault-rtr.service=vault-svc"
      - "traefik.http.services.vault-svc.loadbalancer.server.port=80"
