services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - wireguard_data:/etc/wireguard
    ports:
      - "1194:1194/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=balezeau.fr
      - WG_PORT=1194
      - INSECURE=true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
