services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: my-syncthing
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /www/syncthing:/var/syncthing
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
