services:
  stalwart:
    image: stalwartlabs/stalwart:v0.16
    container_name: stalwart
    restart: unless-stopped
    hostname: mail.balezeau.fr
    networks:
      - treafik_proxy
      - postgres_backend
    volumes:
      - stalwart_etc:/etc/stalwart
      - stalwart_data:/var/lib/stalwart
      - certs:/data/certs:ro
    environment:
      - TZ=Europe/Paris
      - STALWART_DB_PASSWORD=${STALWART_DB_PASSWORD}
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stalwart-rtr.entrypoints=websecure"
      - "traefik.http.routers.stalwart-rtr.rule=Host(`mail.balezeau.fr`) || Host(`autodiscover.balezeau.fr`) || Host(`autoconfig.balezeau.fr`) || Host(`mta-sts.balezeau.fr`)"
      - "traefik.http.routers.stalwart-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.stalwart-rtr.service=stalwart-svc"
      - "traefik.http.services.stalwart-svc.loadbalancer.server.port=8080"

      - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp.service=smtp
      - traefik.tcp.services.smtp.loadbalancer.server.port=25
      - traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.jmap.rule=HostSNI(`*`)
      - traefik.tcp.routers.jmap.tls.passthrough=true
      - traefik.tcp.routers.jmap.entrypoints=websecure
      - traefik.tcp.routers.jmap.service=jmap
      - traefik.tcp.services.jmap.loadbalancer.server.port=443

      - traefik.tcp.routers.smtps.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtps.tls.passthrough=true
      - traefik.tcp.routers.smtps.entrypoints=smtps
      - traefik.tcp.routers.smtps.service=smtps
      - traefik.tcp.services.smtps.loadbalancer.server.port=465
      - traefik.tcp.services.smtps.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.imaps.tls.passthrough=true
      - traefik.tcp.routers.imaps.entrypoints=imaps
      - traefik.tcp.routers.imaps.service=imaps
      - traefik.tcp.services.imaps.loadbalancer.server.port=993
      - traefik.tcp.services.imaps.loadbalancer.proxyProtocol.version=2
