services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2
    container_name: uptime-kuma
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - treafik_proxy
    volumes:
      - uptime_kuma_data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma-rtr.rule=Host(`status.balezeau.fr`)"
      - "traefik.http.routers.uptime-kuma-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.uptime-kuma-rtr.service=uptime-kuma-svc"
      - "traefik.http.services.uptime-kuma-svc.loadbalancer.server.port=3001"
